spring:
  messages:
    basename: static/i18n/messages
  thymeleaf:
    mode: HTML
  datasource:
    username: root
    password: cao981127
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active:
    - dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#自定义属性配置
index: 
  typeNum: 5
  tagNum: 7
  recommendBlogNum: 5
#访客默认头像
comment: 
  avatar: /img/defaultAvatar.png
---
spring:
  thymeleaf:
    cache: false
  profiles: dev
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    cn: debug 
  file: log/blog-dev.log
server:
  port: 80
---
spring:
  profiles: pro
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: warn
    cn: info
  file: log/blog-pro.log
server:
  port: 8080
